service: worlds-worst-auth

provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  environment:
    DYNAMODB_TABLE: worlds-worst-operator-dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - 'arn:aws:dynamodb:us-east-1:437610822210:table/worlds-worst-operator-dev'
        - 'arn:aws:lambda:us-east-1:*:*'

functions:
  authenticate:
    handler: authenticator.authenticate
    timeout: 30
    events:
      - http:
          path: authenticate
          method: post
          cors: true

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true

package:
  exclude:
    - node_modules/**
    - venv/**