dist: xenial

language: python

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

python:
    - "3.7"
    - "3.8-dev"

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v

script:
  - poetry run pytest -q tests/
