dist: xenial

language: python

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

python:
    - "3.7"
    - "3.8-dev"

install:
  - pip install pip==19.2.1
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install -v

script: pytest -q tests/
