service: worlds-worst-operator

provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:InvokeFunction
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - 'arn:aws:dynamodb:us-east-1:437610822210:table/worlds-worst-operator-dev'
        - 'arn:aws:lambda:us-east-1:*:*'

functions:
  route:
    handler: operator.route_tasks_and_response
    timeout: 30
    events:
      - http:
          path: route
          method: post
          cors: true

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true

package:
  exclude:
    - node_modules/**
    - venv/**

resources: # CloudFormation template syntax from here on.
  Resources:
    playersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: playerId
            AttributeType: S
        KeySchema:
          - AttributeName: playerId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST